sources = {'crypto':['https://decryptmedia.com/', 'http://coindesk.com/', 'https://en.cryptonomist.ch/',
            'https://ambcrypto.com/', 'https://tokenhell.com/', 'https://insidebitcoins.com/',
            'https://bitcoinist.com/', 'https://cryptopotato.com/', 'https://coinfomania.com/',
            'http://coinjournal.net/', 'https://btcmanager.com/', 'https://coingeek.com/',
            'https://www.cryptopolitan.com/', 'https://cryptonews.com/news/', 'https://ihodl.com/feed/default/',
            'https://oracletimes.com/', 'https://news.bitcoin.com/', 'https://cointelegraph.com/',
            'https://beincrypto.com/', 'https://cryptobriefing.com/', 'https://coinpedia.org/',
            'https://coinnounce.com/', 'https://coindoo.com/', 'https://thecurrencyanalytics.com/',
            'http://feeds.feedburner.com/kryptomoney', 'https://ourbitcoinnews.com/',
            'https://blokt.com/', 'https://cryptoslate.com/', 'http://www.newsbtc.com/',
            'https://usethebitcoin.com/', 'https://coingape.com/', 'https://altcoinbuzz.io/',
            'https://thetokenist.io/', 'https://www.financemagnates.com/', 'https://zycrypto.com/',
            #'https://bitrates.com/',
            'https://hackernoon.com/', 'https://cryptodaily.co.uk/', 'https://www.koinalert.com/',
            'https://bitcoinmagazine.com/']}