# Generated by Django 3.1.3 on 2020-11-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('published_str', models.CharField(blank=True, max_length=200)),
                ('published', models.DateTimeField(blank=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('source', models.CharField(default='No source', max_length=200)),
                ('categories', models.ManyToManyField(to='stock_apis_BE.Category')),
                ('labels', models.ManyToManyField(to='stock_apis_BE.Label')),
            ],
        ),
    ]
