# Generated by Django 3.1.3 on 2020-11-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_apis_BE', '0002_auto_20201128_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
