# Generated by Django 3.1.3 on 2020-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_apis_BE', '0003_auto_20201130_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(),
        ),
    ]
