# Generated by Django 3.1.3 on 2020-12-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_apis_BE', '0004_auto_20201130_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_str',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
