# Generated by Django 3.1.3 on 2021-02-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_apis_BE', '0005_auto_20201201_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
    ]
